add do not merge label check in ci workflow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -19,6 +19,15 @@ permissions:
   pull-requests: read
 
 jobs:
+  do-not-merge-fail:
+    if: contains(github.event.pull_request.labels.*.name, 'do not merge')
+    runs-on: ubuntu-latest
+    steps:
+      - name: Fail if PR is labeled as 'do not merge'
+        run: |
+          echo "This PR is labeled as 'do not merge' and cannot be merged'
+          exit 1
+
   precommit:
     if: ${{ github.event.pull_request.draft == false }}
     runs-on: ubuntu-latest
